### ISSUE TITLE
Example mktemp use does not typecheck

### ISSUE THREAD

**Issue by maralorn** [luke-clifton/shh#25]
I don’t think the example 

> Use of Haskells concurrency primitives.

from the readme type-checks. When I try to compile:
```
do
  path <- readTrim $ mktemp "-d"
  withCurrentDirectory path $ ls
```
I get
```
    * Couldn't match type `LBS.ByteString' with `[Char]'
      Expected type: FilePath
        Actual type: LBS.ByteString
    * In the first argument of `withCurrentDirectory', namely `path'
      In the expression: withCurrentDirectory path
      In a stmt of a 'do' block: withCurrentDirectory path $ ls
   |
21 |       withCurrentDirectory path $ ls
   |                            ^^^^
```
My solution looks like this:
```
path <- (LT.unpack . LTE.decodeUtf8 <$>) . readTrim $ mktemp "-d"
```
Which is a lot of satisfying the type-checker in comparison to dense code.

**Comment by luke-clifton** [comment]
Thanks (all other docs are typechecked as part of the tests, but the README currently isn't)!

 I recently switched to using ByteString instead of String in a lot of places because `String` was causing all sorts of subtle problems. But maybe some `String` versions of these functions would be worth while.

I'll fix the docs, and look into making it easier.

**Comment by luke-clifton** [comment]
For what it is worth, you don't want to `decodeUtf8` here, because Linux path names aren't utf8 encoded. They are just `ByteStrings`. You are better off using `Data.ByteString.Lazy.Char8.unpack`.
