### ISSUE TITLE
ByteString cannot handle non-English filenames

### ISSUE THREAD

**Issue by mingyuguo** [luke-clifton/shh#44]
First of all, thanks for the great package! I think it works better than Shelly, especially when it comes to scripting involving fzf.

Say, I use template haskell and created variable libreoffice.  I cannot do

libreoffice "文件.docx"

because it automatically forces the file name to bytestring and libreoffice cannot understand it.

My workaround is that when it comes to non English name, I will do

writeFile "/tmp/sometmp.log" "libreoffice '文件.docx'" >> sh "/tmp/sometmp.log"

**Comment by luke-clifton** [comment]
Yeah, this is a known problem primarily because we are using `System.Process` which requires us to roundtrip through `String` and then uses some magic encoding stuff. I've been trying to avoid assuming UTF8 encoding (linux paths and arguments are not utf8 encoded, they are just raw bytes). In the long run I'm going to move away from the `String` interfaces which will solve this problem. In the short term, I'm going to temporarily add the assumption that paths are UTF-8 encoded because that will actually solve more problems than it causes.

**Comment by luke-clifton** [comment]
I just released 0.7.1.0 to Hackage.

```haskell
λ exe "echo" "test" &> Truncate (Data.ByteString.Lazy.UTF8.fromString "文件")
λ exe "cat" "文件"
test
```

You need to be aware that any command that accepts a `ByteString` literal (such as `Truncate` above) is going to need to be specifically encoded because GHC doesn't do anything clever when using `OverloadedStrings` and `ByteStrings` together....

```haskell
λ "文件" :: L.ByteString  -- Incorrect result
"\135\246"
λ Data.ByteString.Lazy.UTF8.fromString "文件" :: L.ByteString -- Correct result
"\230\150\135\228\187\182"
```

Anything that accepts an `ExecArg` constrained argument (such as commands generated with the template haskell helper) can accept either `String` or `ByteString`. If you are using `OverloadedStrings` and `ExtendedDefaultRules` it should infer `String` and just work, but if for whatever reason it infers `ByteString` you will run into problems.

Ultimately, I think the `OverloadedStrings` needs to be fixed in GHC to not truncate the chars. I might propose that at some point.

Let me know if this fixes your problem.

**Comment by mingyuguo** [comment]
Thanks very much for the super fast response!

I ported about 400 lines of code from Shelly to Shh. I made a few helper functions that I use a lot. I feel it's inconvenient to get away from String as FilePath and getArgs are both in String. Also, there are many String functions that are handy like replace, splitOn, takeEnd, etc. So I decide to keep the Haskell part String only (while leaving the piping part ByteString). That is, whenever I capture something (for use in Haskell), I capture it directly into String, and whenever I need pureProc, I use pureProcString.

captureFirstLineString :: Shell io => io String
captureFirstLineString = readInput (return . firstLine . toString)

captureFirstWordString :: Shell io => io String
captureFirstWordString = readInput (return . firstWord . toString)

pureProcString :: Shell io => (String -> String) -> io ()
pureProcString f = pureProc (fromString . f . toString)

**Comment by luke-clifton** [comment]
Hi @mingyuguo, Yeah, `String` is convenient to use. I wanted to keep this interface as raw as possible to not artificially limit use cases (I often need to work with binary files).

I hope your issue is solved now though? I'm going to close this issue, feel free to re-open it if you are still having problems with filenames.

**Comment by luke-clifton** [comment]
I finally figured out how GHC encodes `FilePath`s, so this has gone through another iteration. It should now work for any filename you can throw at it (but still be aware of `ByteString` literals and their truncation)
